python3 slim_model.py --config configs/transcripts.json --ckpt-step 406
python3 slim_model.py --config configs/transcripts.json --ckpt-step 379
python3 slim_model.py --config configs/transcripts.json --ckpt-step 352
python3 slim_model.py --config configs/transcripts.json --ckpt-step 325
python3 slim_model.py --config configs/transcripts.json --ckpt-step 298
python3 slim_model.py --config configs/transcripts.json --ckpt-step 271
python3 slim_model.py --config configs/transcripts.json --ckpt-step 244
python3 slim_model.py --config configs/transcripts.json --ckpt-step 217
python3 slim_model.py --config configs/transcripts.json --ckpt-step 190
python3 slim_model.py --config configs/transcripts.json --ckpt-step 163
python3 slim_model.py --config configs/transcripts.json --ckpt-step 136
python3 slim_model.py --config configs/transcripts.json --ckpt-step 109
python3 slim_model.py --config configs/transcripts.json --ckpt-step 82
python3 slim_model.py --config configs/transcripts.json --ckpt-step 55
python3 slim_model.py --config configs/transcripts.json --ckpt-step 28
