python3 to_hf_weights.py --input-ckpt gs://aarrfsf/transcripts/_slim/step_432 --config config/slim_transcripts.json --output-path gs://aarrfsf/transcripts/hf/
python3 to_hf_weights.py --input-ckpt gs://aarrfsf/transcripts/_slim/step_406 --config config/slim_transcripts.json --output-path gs://aarrfsf/transcripts/hf/
python3 to_hf_weights.py --input-ckpt gs://aarrfsf/transcripts/_slim/step_379 --config config/slim_transcripts.json --output-path gs://aarrfsf/transcripts/hf/
python3 to_hf_weights.py --input-ckpt gs://aarrfsf/transcripts/_slim/step_352 --config config/slim_transcripts.json --output-path gs://aarrfsf/transcripts/hf/
python3 to_hf_weights.py --input-ckpt gs://aarrfsf/transcripts/_slim/step_325 --config config/slim_transcripts.json --output-path gs://aarrfsf/transcripts/hf/
python3 to_hf_weights.py --input-ckpt gs://aarrfsf/transcripts/_slim/step_298 --config config/slim_transcripts.json --output-path gs://aarrfsf/transcripts/hf/
python3 to_hf_weights.py --input-ckpt gs://aarrfsf/transcripts/_slim/step_271 --config config/slim_transcripts.json --output-path gs://aarrfsf/transcripts/hf/
python3 to_hf_weights.py --input-ckpt gs://aarrfsf/transcripts/_slim/step_244 --config config/slim_transcripts.json --output-path gs://aarrfsf/transcripts/hf/
python3 to_hf_weights.py --input-ckpt gs://aarrfsf/transcripts/_slim/step_217 --config config/slim_transcripts.json --output-path gs://aarrfsf/transcripts/hf/
python3 to_hf_weights.py --input-ckpt gs://aarrfsf/transcripts/_slim/step_190 --config config/slim_transcripts.json --output-path gs://aarrfsf/transcripts/hf/
python3 to_hf_weights.py --input-ckpt gs://aarrfsf/transcripts/_slim/step_163 --config config/slim_transcripts.json --output-path gs://aarrfsf/transcripts/hf/
python3 to_hf_weights.py --input-ckpt gs://aarrfsf/transcripts/_slim/step_136 --config config/slim_transcripts.json --output-path gs://aarrfsf/transcripts/hf/
python3 to_hf_weights.py --input-ckpt gs://aarrfsf/transcripts/_slim/step_109 --config config/slim_transcripts.json --output-path gs://aarrfsf/transcripts/hf/
python3 to_hf_weights.py --input-ckpt gs://aarrfsf/transcripts/_slim/step_82 --config config/slim_transcripts.json --output-path gs://aarrfsf/transcripts/hf/
python3 to_hf_weights.py --input-ckpt gs://aarrfsf/transcripts/_slim/step_55 --config config/slim_transcripts.json --output-path gs://aarrfsf/transcripts/hf/
python3 to_hf_weights.py --input-ckpt gs://aarrfsf/transcripts/_slim/step_28 --config config/slim_transcripts.json --output-path gs://aarrfsf/transcripts/hf/
